[phases.setup]
nixPkgs = ["php83", "php83Extensions.curl", "php83Extensions.pdo_pgsql", "php83Extensions.mbstring", "php83Extensions.openssl"]

[variables]
PHP_CLI_SERVER_WORKERS = "4"

[start]
cmd = "sh -c \"php -S 0.0.0.0:$PORT -t . router.php\""
